# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "87a43707cf662d4259f86e37110986224826959fd6c8055d98b355ec2d565289"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3883bebca7165c9ad0e7b7bd6b3ec41718f2346611e78967fdb141789542e500"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2e49567c76c47cc178f2fb11b9efc202d9b9bb7d39798d7d1e34484eeaaa457a"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0abcbac78006465a18eb13918b7f2e2004ec2df970f2e213adba301e7f833a7b"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "faultline"
  desc "HTTP and HTTPS fault-injection proxy for development and testing"
  homepage "https://github.com/josipmusa/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/faultline"]
    end
  end

  # No zap stanza required
end
