# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "1b005e1aa1bbffba3e0ee21ab1b7528cfe8937c62587cc4a3f768014ade50324"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c263e44f723b1fda5f9245be66ef7bedf6147c30219bb09ad129074c2b98c05"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae40cf0bec1830330faa52ee3c279491b3f07c6180befbb58c400d6995cb0072"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb87df3f4dc04190132c94ad7796a911fc66a494d4b9198ebcb443bb056599e5"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "faultline"
  desc "HTTP and HTTPS fault-injection proxy for development and testing"
  homepage "https://github.com/josipmusa/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/faultline"]
    end
  end

  # No zap stanza required
end
