# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "368d3cee2ee73bfb896ad5c006d3e81f931c24072e996d91c32c63b7a8095a80"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60459bef6daa6935b1558c5269622f4ef31849292860028571d1f0c80cb03ac5"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3a1bd250e290a7e937a69ce7dcc653900e6eff99c0402d7487b5fadeb3b0e8e6"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d223ae8be69ddded58a120af40f2856dac2b387d87475cb0a93aa8d064cbd89"
      url "https://github.com/josipmusa/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "faultline"
  desc "HTTP and HTTPS fault-injection proxy for development and testing"
  homepage "https://github.com/josipmusa/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/faultline"]
    end
  end

  # No zap stanza required
end
